// <auto-generated />
using System;
using FeedbackAnalyze.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FeedbackAnalyze.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.3.24172.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FeedbackAnalyze.Data.Entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Sentiment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("FeedbackAnalyze.Data.Entities.FeedbackSentence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BeginOffset")
                        .HasColumnType("integer");

                    b.Property<int>("EndOffset")
                        .HasColumnType("integer");

                    b.Property<int>("ProductFeedbackId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductFeedbackId");

                    b.ToTable("FeedbackSentences");
                });

            modelBuilder.Entity("FeedbackAnalyze.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FeedbackAnalyze.Data.Entities.ProductFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Sentiment")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductFeedbacks");
                });

            modelBuilder.Entity("FeedbackFeedbackSentence", b =>
                {
                    b.Property<int>("FeedbackSentencesId")
                        .HasColumnType("integer");

                    b.Property<int>("FeedbacksId")
                        .HasColumnType("integer");

                    b.HasKey("FeedbackSentencesId", "FeedbacksId");

                    b.HasIndex("FeedbacksId");

                    b.ToTable("FeedbackFeedbackSentence");
                });

            modelBuilder.Entity("FeedbackAnalyze.Data.Entities.FeedbackSentence", b =>
                {
                    b.HasOne("FeedbackAnalyze.Data.Entities.ProductFeedback", "ProductFeedback")
                        .WithMany("FeedbackSentences")
                        .HasForeignKey("ProductFeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductFeedback");
                });

            modelBuilder.Entity("FeedbackAnalyze.Data.Entities.ProductFeedback", b =>
                {
                    b.HasOne("FeedbackAnalyze.Data.Entities.Product", "Product")
                        .WithMany("ProductFeedbacks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FeedbackFeedbackSentence", b =>
                {
                    b.HasOne("FeedbackAnalyze.Data.Entities.FeedbackSentence", null)
                        .WithMany()
                        .HasForeignKey("FeedbackSentencesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FeedbackAnalyze.Data.Entities.Feedback", null)
                        .WithMany()
                        .HasForeignKey("FeedbacksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FeedbackAnalyze.Data.Entities.Product", b =>
                {
                    b.Navigation("ProductFeedbacks");
                });

            modelBuilder.Entity("FeedbackAnalyze.Data.Entities.ProductFeedback", b =>
                {
                    b.Navigation("FeedbackSentences");
                });
#pragma warning restore 612, 618
        }
    }
}
